/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.util.Arrays;

/**
 *
 * @author nkotieno
 */
public class Menu3 extends javax.swing.JFrame {

    //Combo boxes
    static String st1, st2, st3, c1, c2, c3, o1, o2, o3, m1, m2, m3;
    //checkbox
    static String stw1, stw2, stw3, ch1, ch2, ch3, or1, or2, or3, ma1, ma2, ma3;
    static String[][][] food;
    static String[][] herbss, meatt, cheesee, veggiess;

    /**
     * Creates new form Menu3
     *
     * @param prop
     */
    public Menu3(String[][][] prop, String[][] herbs, String[][] meat, String[][] cheese, String[][] veggies) {
        initComponents();
        food = prop;
        this.herbss = herbs;
        this.meatt = meat;
        this.cheesee = cheese;
        this.veggiess = veggies; 
        System.out.println("menu3");
        System.out.println(Arrays.deepToString(meat));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkoutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        strawberrys = new javax.swing.JCheckBox();
        strawberrym = new javax.swing.JCheckBox();
        strawberryl = new javax.swing.JCheckBox();
        chocolatel = new javax.swing.JCheckBox();
        chocolatesBox = new javax.swing.JComboBox<>();
        chocolatemBox = new javax.swing.JComboBox<>();
        chocolatelBox = new javax.swing.JComboBox<>();
        strawberrysBox = new javax.swing.JComboBox<>();
        strawberrymBox = new javax.swing.JComboBox<>();
        strawberrylBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chocolates = new javax.swing.JCheckBox();
        chocolatem = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        oranges = new javax.swing.JCheckBox();
        orangesBox = new javax.swing.JComboBox<>();
        orangem = new javax.swing.JCheckBox();
        orangemBox = new javax.swing.JComboBox<>();
        orangel = new javax.swing.JCheckBox();
        orangelBox = new javax.swing.JComboBox<>();
        mangos = new javax.swing.JCheckBox();
        mangosBox = new javax.swing.JComboBox<>();
        mangom = new javax.swing.JCheckBox();
        mangomBox = new javax.swing.JComboBox<>();
        mangol = new javax.swing.JCheckBox();
        mangolBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel1.setText("DRINKS");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel2.setText("Juices");

        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel3.setText("Milkshakes");

        strawberrys.setText("Strawberry Small (R35)");
        strawberrys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberrysActionPerformed(evt);
            }
        });

        strawberrym.setText("Strawberry Medium (R45)");
        strawberrym.setToolTipText("");

        strawberryl.setText("Strawberry Large (R65)");

        chocolatel.setText("Chocolate Large (R65)");

        chocolatesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        chocolatemBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        chocolatelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        strawberrysBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        strawberrymBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        strawberrylBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 102));
        jLabel5.setText("Strawberry Milkshake ");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("Chocolate Milkshake");

        chocolates.setText("Chocolate Small (R35)");

        chocolatem.setText("Chocolate Medium (R45)");

        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("Orange ");
        jLabel8.setToolTipText("");

        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("Mango ");

        oranges.setText("Orange Small (R45)");

        orangesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        orangem.setText("Orange Medium (R65)");

        orangemBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        orangel.setText("Orange Large (R75)");

        orangelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        mangos.setText("Mango Small (R45)");

        mangosBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        mangom.setText("Mango Medium (R65)");

        mangomBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        mangol.setText("Mango Large (R75)");

        mangolBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addGap(125, 125, 125))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(strawberrys)
                                        .addComponent(strawberrym)
                                        .addComponent(strawberryl))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(strawberrymBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(strawberrysBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(strawberrylBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(80, 80, 80)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(chocolates)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chocolatesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(chocolatel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(chocolatelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(chocolatem)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chocolatemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(337, 337, 337)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel2)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(orangem)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(orangemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(oranges)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(orangesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(orangel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(orangelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(mangos)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mangosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(mangom)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mangomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(mangol)
                                            .addGap(18, 18, 18)
                                            .addComponent(mangolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(20, 20, 20))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(296, 296, 296)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(605, Short.MAX_VALUE)
                        .addComponent(checkoutButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strawberrys)
                    .addComponent(strawberrysBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chocolates)
                    .addComponent(chocolatesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strawberrym)
                    .addComponent(strawberrymBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chocolatem)
                    .addComponent(chocolatemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strawberryl)
                    .addComponent(strawberrylBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chocolatel)
                    .addComponent(chocolatelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oranges)
                    .addComponent(orangesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangos)
                    .addComponent(mangosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orangem)
                    .addComponent(orangemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangom)
                    .addComponent(mangomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orangel)
                    .addComponent(orangelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangol)
                    .addComponent(mangolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(checkoutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String[] addTO(int n, String arr[], String x) {
        int i;
//create anew array and cast to String
        String[] newarr = new String[n + 1];

        // insert the elements from the old array into the new array 
        // insert all elements till n  
        for (i = 0; i < n; i++) {
            newarr[i] = arr[i];
        }

        newarr[n] = x;

        return newarr;
    }

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        String[] milkShakes = {};
        String[] milkShakesCount = {};
        String[] milkShakesPrice = {};
        String[] Juices = {};
        String[] JuicesCount = {};
        String[] JuicesPrices = {};
        //Strawberry milkshake
        if (strawberrys.isSelected()) {
            stw1 = (String) strawberrysBox.getSelectedItem();
            st1 = st1 + strawberrys.getText() + "\n";

            milkShakes = addTO(milkShakes.length,
                    milkShakes, "Strayberry Small");
            milkShakesCount = addTO(milkShakesCount.length,
                    milkShakesCount,
                    stw1);
            milkShakesPrice = addTO(milkShakesPrice.length,
                    milkShakesPrice,
                    "35");
        }
        if (strawberrym.isSelected()) {
            stw2 = (String) strawberrymBox.getSelectedItem();
            st2 = st2 + strawberrym.getText() + "\n";
            milkShakes = addTO(milkShakes.length,
                    milkShakes, "Strayberry Medium");
            milkShakesCount = addTO(milkShakesCount.length,
                    milkShakesCount,
                    stw2);
            milkShakesPrice = addTO(milkShakesPrice.length,
                    milkShakesPrice,
                    "45");
        }
        if (strawberryl.isSelected()) {
            stw3 = (String) strawberrylBox.getSelectedItem();
            st3 = st3 + strawberryl.getText() + "\n";
            milkShakes = addTO(milkShakes.length,
                    milkShakes, "Strayberry Large");
            milkShakesCount = addTO(milkShakesCount.length,
                    milkShakesCount,
                    stw3);
            milkShakesPrice = addTO(milkShakesPrice.length,
                    milkShakesPrice,
                    "65");
        }

        //Chocolate milkshake 
        if (chocolates.isSelected()) {
            c1 = (String) chocolatesBox.getSelectedItem();
            ch1 = ch1 + chocolates.getText() + "\n";
            milkShakes = addTO(milkShakes.length,
                    milkShakes, "Chocolate Small");
            milkShakesCount = addTO(milkShakesCount.length,
                    milkShakesCount,
                    c1);
            milkShakesPrice = addTO(milkShakesPrice.length,
                    milkShakesPrice,
                    "35");
        }
        if (chocolatem.isSelected()) {
            c2 = (String) chocolatemBox.getSelectedItem();
            ch2 = ch2 + chocolatem.getText() + "\n";
            milkShakes = addTO(milkShakes.length,
                    milkShakes, "Chocolate Medium");
            milkShakesCount = addTO(milkShakesCount.length,
                    milkShakesCount,
                    c2);
            milkShakesPrice = addTO(milkShakesPrice.length,
                    milkShakesPrice,
                    "45");

        }
        if (chocolatel.isSelected()) {
            c3 = (String) chocolatelBox.getSelectedItem();
            ch3 = ch3 + chocolatel.getText() + "\n";
            milkShakes = addTO(milkShakes.length,
                    milkShakes, "Chocolate Large");
            milkShakesCount = addTO(milkShakesCount.length,
                    milkShakesCount,
                    c3);
            milkShakesPrice = addTO(milkShakesPrice.length,
                    milkShakesPrice,
                    "65");
        }

        //Orange juice 
        if (oranges.isSelected()) {
            o1 = (String) orangesBox.getSelectedItem();
            or1 = or1 + oranges.getText() + "\n";
            Juices = addTO(Juices.length,
                    Juices, "Orange Small");
            JuicesCount = addTO(JuicesCount.length, JuicesCount,
                    o1);
            JuicesPrices = addTO(JuicesPrices.length,
                    JuicesPrices,
                    "45");
        }
        if (orangem.isSelected()) {
            o2 = (String) orangemBox.getSelectedItem();
            or2 = or2 + orangem.getText() + "\n";
            Juices = addTO(Juices.length,
                    Juices, "Orange Medium");
            JuicesCount = addTO(JuicesCount.length, JuicesCount,
                    o2);
            JuicesPrices = addTO(JuicesPrices.length,
                    JuicesPrices,
                    "65");
        }
        if (orangel.isSelected()) {
            o3 = (String) orangelBox.getSelectedItem();
            or3 = or3 + orangel.getText() + "\n";
            Juices = addTO(Juices.length,
                    Juices, "Orange Large");
            JuicesCount = addTO(JuicesCount.length, JuicesCount,
                    o3);
            JuicesPrices = addTO(JuicesPrices.length,
                    JuicesPrices,
                    "75");
        }

        //Mango juice 
        if (mangos.isSelected()) {
            m1 = (String) mangosBox.getSelectedItem();
            ma1 = ma1 + mangos.getText() + "\n";
            Juices = addTO(Juices.length,
                    Juices, "Mango Small");
            JuicesCount = addTO(JuicesCount.length, JuicesCount,
                    m1);
            JuicesPrices = addTO(JuicesPrices.length,
                    JuicesPrices,
                    "45");
        }
        if (mangom.isSelected()) {
            m2 = (String) mangomBox.getSelectedItem();
            ma2 = ma2 + mangom.getText() + "\n";
            Juices = addTO(Juices.length,
                    Juices, "mango Medium");

            JuicesCount = addTO(JuicesCount.length, JuicesCount,
                    m2);
            JuicesPrices = addTO(JuicesPrices.length,
                    JuicesPrices,
                    "65");
        }
        if (mangol.isSelected()) {
            m3 = (String) mangolBox.getSelectedItem();
            ma3 = ma3 + mangol.getText() + "\n";
            Juices = addTO(Juices.length,
                    Juices, "Mango Large");
            JuicesCount = addTO(JuicesCount.length, JuicesCount,
                    (String) mangolBox.getSelectedItem());

            JuicesPrices = addTO(JuicesPrices.length,
                    JuicesPrices,
                    "75");
        }
        String[][] milkShakeFin = {
            milkShakes,
            milkShakesCount,
            milkShakesPrice
        };
        String[][] JuicesFin = {
            Juices,
            JuicesCount,
            JuicesPrices
        };
        new Checkout(food,milkShakeFin, JuicesFin,this.herbss, meatt, cheesee, veggiess).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void strawberrysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberrysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strawberrysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu3(food,herbss, meatt, cheesee, veggiess).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkoutButton;
    private javax.swing.JCheckBox chocolatel;
    private javax.swing.JComboBox<String> chocolatelBox;
    private javax.swing.JCheckBox chocolatem;
    private javax.swing.JComboBox<String> chocolatemBox;
    private javax.swing.JCheckBox chocolates;
    private javax.swing.JComboBox<String> chocolatesBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox mangol;
    private javax.swing.JComboBox<String> mangolBox;
    private javax.swing.JCheckBox mangom;
    private javax.swing.JComboBox<String> mangomBox;
    private javax.swing.JCheckBox mangos;
    private javax.swing.JComboBox<String> mangosBox;
    private javax.swing.JCheckBox orangel;
    private javax.swing.JComboBox<String> orangelBox;
    private javax.swing.JCheckBox orangem;
    private javax.swing.JComboBox<String> orangemBox;
    private javax.swing.JCheckBox oranges;
    private javax.swing.JComboBox<String> orangesBox;
    private javax.swing.JCheckBox strawberryl;
    private javax.swing.JComboBox<String> strawberrylBox;
    private javax.swing.JCheckBox strawberrym;
    private javax.swing.JComboBox<String> strawberrymBox;
    private javax.swing.JCheckBox strawberrys;
    private javax.swing.JComboBox<String> strawberrysBox;
    // End of variables declaration//GEN-END:variables
}
